import { jsPDF } from 'jspdf';
import { Document, Packer, Paragraph, ImageRun } from 'docx';

export type SupportedFormat = 'webp' | 'png' | 'jpeg' | 'bmp' | 'pdf' | 'svg' | 'ico' | 'tiff' | 'docx' | 'md' | 'txt';

export interface ConversionOptions {
  format: SupportedFormat;
  quality?: number;
  enhance?: {
    brightness?: number;
    contrast?: number;
    gamma?: number;
    sharpen?: boolean;
  };
}

export const convertImage = async (file: File, options: ConversionOptions): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      const img = new Image();
      img.onload = async () => {
        const canvas = document.createElement('canvas');
        canvas.width = img.width;
        canvas.height = img.height;
        const ctx = canvas.getContext('2d');
        if (!ctx) {
          reject(new Error('Failed to get canvas context'));
          return;
        }

        // Apply filters if enhancement is requested
        let filterString = '';
        if (options.enhance) {
          if (options.enhance.brightness !== undefined) filterString += `brightness(${options.enhance.brightness * 100}%) `;
          if (options.enhance.contrast !== undefined) filterString += `contrast(${options.enhance.contrast * 100}%) `;
        }
        ctx.filter = filterString.trim() || 'none';

        ctx.drawImage(img, 0, 0);

        // --- CUSTOM LOGIC FOR DOCUMENTS ---

        // PDF Logic
        if (options.format === 'pdf') {
          const pdf = new jsPDF({
            orientation: img.width > img.height ? 'landscape' : 'portrait',
            unit: 'px',
            format: [img.width, img.height]
          });
          pdf.addImage(img, 'JPEG', 0, 0, img.width, img.height);
          resolve(pdf.output('datauristring'));
          return;
        }

        // Word (DOCX) Logic
        if (options.format === 'docx') {
          try {
            const base64Data = canvas.toDataURL('image/png').split(',')[1];
            const doc = new Document({
              sections: [{
                children: [
                  new Paragraph(`${file.name} - Converted by OmniConvert`),
                  new Paragraph({
                    children: [
                      new ImageRun({
                        data: Uint8Array.from(atob(base64Data).split('').map(c => c.charCodeAt(0))),
                        transformation: { width: img.width > 600 ? 600 : img.width, height: (img.width > 600 ? 600 : img.width) * (img.height / img.width) },
                        type: 'png'
                      })
                    ]
                  })
                ]
              }]
            });
            const blob = await Packer.toBlob(doc);
            resolve(URL.createObjectURL(blob));
          } catch (err) {
            reject(err);
          }
          return;
        }

        // Markdown (MD) Logic
        if (options.format === 'md') {
          const mdContent = `# Converted Image: ${file.name}\n\n![${file.name}](${e.target?.result})\n\n---\n*Generated by OmniConvert*`;
          const blob = new Blob([mdContent], { type: 'text/markdown' });
          resolve(URL.createObjectURL(blob));
          return;
        }

        // Metadata (TXT) Logic
        if (options.format === 'txt') {
          const metaInfo = `OMNICONVERT METADATA REPORT\n=========================\nFile Name: ${file.name}\nDimensions: ${img.width}x${img.height}px\nOriginal Size: ${(file.size / 1024).toFixed(2)} KB\nDetected Format: ${file.type}\nLast Modified: ${new Date(file.lastModified).toLocaleString()}\n=========================`;
          const blob = new Blob([metaInfo], { type: 'text/plain' });
          resolve(URL.createObjectURL(blob));
          return;
        }

        // SVG (raster wrap) Logic
        if (options.format === 'svg') {
          const svgString = `<svg xmlns="http://www.w3.org/2000/svg" width="${img.width}" height="${img.height}">
            <image href="${e.target?.result}" width="${img.width}" height="${img.height}" />
          </svg>`;
          const blob = new Blob([svgString], { type: 'image/svg+xml' });
          resolve(URL.createObjectURL(blob));
          return;
        }

        // --- STANDARD RASTER FORMATS ---
        const mimeType = `image/${options.format === 'jpeg' ? 'jpeg' : (options.format === 'ico' ? 'x-icon' : options.format)}`;
        const dataUrl = canvas.toDataURL(mimeType, options.quality || 0.9);
        resolve(dataUrl);
      };
      img.onerror = () => reject(new Error('Failed to load image'));
      img.src = e.target?.result as string;
    };
    reader.onerror = () => reject(new Error('Failed to read file'));
    reader.readAsDataURL(file);
  });
};
